# Generated by Django 3.2.7

from django.contrib.gis.db import models as gis_models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_property_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='location',
            field=gis_models.PointField(
                geography=True,
                blank=True,
                null=True,
                verbose_name='Geographic Location',
                help_text='Store the geographic coordinates (longitude, latitude)',
            ),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['price'], name='property_price_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['created_at'], name='property_created_at_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['city'], name='property_city_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['bedrooms'], name='property_bedrooms_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['advert_type'], name='property_advert_type_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['property_type'], name='property_property_type_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=gis_models.GistIndex(fields=['location'], name='property_location_gist_idx'),
        ),
    ]
